# Generated by Django 4.2.3 on 2023-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="weigth",
            new_name="weight",
        ),
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Not informed", "Notinformed"),
                ],
                default="Not informed",
                max_length=20,
            ),
        ),
    ]
