# Generated by Django 4.2.3 on 2023-07-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_rename_weigth_pet_weight_alter_pet_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Not Informed", "Notinformed"),
                ],
                default="Not Informed",
                max_length=20,
            ),
        ),
    ]
